### ISSUE TITLE
7-day drop in new cases highlights nature of data sources

### ISSUE THREAD

**Issue by bobuntu** [reustle/covid19japan-data#29]
Every Monday the daily new cases drops dramatically, and peaks again the next day. It means 2 things, actually 3: [1] what we get to see is already over a day old, and [2] on Sundays many cases aren’t reported since [3] the data is collected manually.

There is mounting sentiment that not the whole picture is being told, as the magazine The Economist claimed [excess covid-19 deaths](https://t.co/v3x8RZRoCX) can be 2x the officially reported deaths in some countries. Could that be the case for daily new cases in Japan?

Are there plans to fix this gap between what is told, and what is really happening?

**Comment by liquidx** [comment]
How do you suggest we fix this?

**Comment by bobuntu** [comment]
Neither you or anybody else has a say on where the data comes from or how it is collected. And that’s okay, as long as a disclaimer is published to acknowledge the discrepancy.

**Comment by bobuntu** [comment]
I have seen the discrepancies you list, but this **weekend drop** isn’t acknowledged and it could potentially be misinterpreted.

**Comment by damupenda** [comment]
Hospitals are basically closed on the weekends in Japan. Minimum staff for inpatients only. All departments are closed for the most part. So no surprise that the numbers drop on Saturday and hit their lowest point on Sunday.
________________________________

**Comment by liquidx** [comment]
Thanks for the analysis. I tried to solve it by adding a 7-day average line on new cases so you can see the trend without the day-by-day fluctuations (e.g. counting 7 days would smooth out the dips on Sunday and Monday.

**Comment by bobuntu** [comment]
That is definitely one way of solving it. Thanks!

**Comment by bobuntu** [comment]
I’ve thought some more on what else could help. But to my knowledge nothing comes up, and so the 7-day average is the best solution. Closing the issue now...
