### ISSUE TITLE
Recovered of Tokyo seems not to be updated for a while

### ISSUE THREAD

**Issue by tkyh0125** [reustle/covid19japan-data#34]
Forgive me if this topic is not for here.
I'm not sure where I can report.

As the title stated, I suspect the number of recovered of Tokyo seems not to be changed for a while.
The webpage below said almost thousands "Discharged", while covid19japan.com says 59 "Recovered".
https://stopcovid19.metro.tokyo.lg.jp/en

This might intentional... But just I want to let you know in case you're not aware of...

**Comment by liquidx** [comment]
Thanks for highlighting that. 

The stopcovid19 dashboard is counting both recovered and patients who are confirmed but not put in a hospital (e.g. being quarantined in hotels). We are getting our recovered numbers from the MHLW which only counts patients that have tested negative. 

We're discussing whether we need to add a clarification to this somewhere on the page.

**Comment by tkyh0125** [comment]
Thank you for the clarification.
I understood the difference.

I still believe 59 recovered is too low considering total cases in Tokyo.
But it's not your bad, but the sources'.

**Comment by l15n** [comment]
Perhaps we could shift to using "Discharged" rather than "Recovered"? Although these terms were almost synonomous, "discharged" is the more accurate term to describe 退院者. I believe most authorities aren't literally reporting 回復者 but rather 退院者

**Comment by tkyh0125** [comment]
Yes, I understood the difference.
And I'm not sure it's a good idea to use "Discharged" instead of "Recovered".
Since "Discharged" still includes active people.

So don't mind my murmurs guys.
I still believe covid19japan is the best outlet. Thank you for your work.
