### ISSUE TITLE
Incomplete data in "Sum By Days" on the Google spreadsheet

### ISSUE THREAD

**Issue by Kryptos-FR** [reustle/covid19japan-data#52]
I left two comments in the last two weeks on https://docs.google.com/spreadsheets/d/1zdMR6BhAU00Ol_4WfYmZRmjUYZp_RkwOZMeRGUX4zBY/view#gid=1690900878, but apparently nobody looks at that form anymore. So I'm opening an issue here.

The sheet "Sum by Day" is missing data on the "confirmed" column. It has been the case every time a new sheet has been opened for a prefecture and data moved from the "Patient data" sheet to that new one. Interestingly, the data on the "Decesased (auto)" column does include all prefecture sheets.

Consequently, the total number of cases is missing about 3000 cases. That makes this sheet unusable (until two weeks ago I was copying the data manually into my own data sheet on my PC).

Should be a 10s fix, unfortunately I don't have write access to the Google sheet.

**Comment by liquidx** [comment]
If you could, try use the JSON file that's in this repo which is updated every 15 minutes and properly aggregates all the data properly. We only do just enough on the spreadsheet to help data input. 

Nevertheless, I updated the formula in the sheet to account for the missing tabs.

Thanks for letting us know.

**Comment by Kryptos-FR** [comment]
Thanks. I don't use the JSON because I just read the spreadhseet manually as a human being and JSON is not really human readable (at least not easily 😉).
