### ISSUE TITLE
Can't find Iwate prefecture data

### ISSUE THREAD

**Issue by LiZHU7594** [reustle/covid19japan-data#54]
There is Iwate prefecture in googleSheet [COVID19 Japan Patient Database (Google Spreadsheet)](https://docs.google.com/spreadsheets/d/e/2PACX-1vRj0RcpTglCmtDVP1RRx21ZwteYU2Y_8JExoeIVbMG1onsmHHah3DwI2HwunY8FOU3eqme82th_hYWF/pubhtml) but it isn't contained in [Daily summary and Per-prefecture summary](https://data.covid19japan.com/summary/latest.json). Why isn't it contained?

**Comment by liquidx** [comment]
There are no confirmed cases in Iwate, so it doesn't show up.
