### ISSUE TITLE
Tochigi Prefecture Recoveries - Aug 12

### ISSUE THREAD

**Issue by akatz2** [reustle/covid19japan-data#66]
Hi.  I believe the recoveries for Tochigi Prefecture are incorrect for August 12th.  They are currently listed at 1808, but there are only 261 cases in the prefecture.  According to the linked dashboard (https://covid19-tochigi.netlify.app/en), the number should be closer to 182.

**Comment by liquidx** [comment]
Thanks for letting us know. I fixed it the day after, but forgot to check this issue here.
