### ISSUE TITLE
Aomori Prefecture Recoveries Sep 3rd

### ISSUE THREAD

**Issue by Pokere** [reustle/covid19japan-data#70]
As of September 3rd Aomori Prefecture only have 2 active cases as opposed to the 5 active cases shown. These three extra may be the ones connected to the American Military Base.

**Comment by liquidx** [comment]
You're right, we did count them but the prefecture doesn't track their recovery. I've removed them from the count now so it will be back down to two active cases when the data next refreshes. Thanks!
