### ISSUE TITLE
How can I obtain historic region level data?

### ISSUE THREAD

**Issue by CosmicGans** [reustle/covid19japan-data#75]
The website has charts for each region (Kansai, Kanto, etc.). Is there an endpoint where I could obtain the raw data/ or alternatively find a source that gives me the same chart but with an x-axis that is labelled with the dates? 

Great thanks for the awesome dashboard!

**Comment by liquidx** [comment]
If the data in docs/summary/latest.json isn't enough (it has an array of the confirmed/recovered numbers with historical data), then you will need to post-process directly from the data that comes from the spreadsheet. 

If you want to see how this works, the code is in src/charts.js which is used to generate all the SVG charts the site uses.

**Comment by CosmicGans** [comment]
Thanks, closing the issue!
