### ISSUE TITLE
Death Data Discrepancy on January 19th 2021

### ISSUE THREAD

**Issue by Ryllau** [reustle/covid19japan-data#81]
Hello! 
In regards to death data on January 19th 2021.  

Based on the data reported in docs/summary/latest.json, it looks like the cumulative deaths in the morning of January 19th was reported at 4366 and later in the day was reported at 4680. However, the daily deaths only shows an increase of 104 deaths. 

Would you mind explaining this discrepancy? Thank you!

**Comment by liquidx** [comment]
It's likely because on Jan 19 I went back to resolve some missing deaths from the last three months before. If you diff the patients data file between that period it'll likely show what was corrected.

How did you know that the cumulative number changed?

**Comment by Ryllau** [comment]
Thanks for the response! 
Just to clarify what you mentioned above, does that mean all of the missing deaths from the past three months were added to the cumulative death total on the 19th? 

To answer your question, my team has been following this repository (specifically latest.json summary file) for sometime and doing our own data collection effort. In a time series chart that we have created using the cumulative data, a user noticed a large increase of cumulative deaths from the 18th to the 19th as mentioned above. When cross referencing the spike with the daily death cases from your dashboard, there is a discrepancy. We just want to sort out where these extra cases are coming from so we can notify users of the issue.

**Comment by liquidx** [comment]
All the deaths were accounted for in the day they were reported. I don't know if you're looking at the prefecture splits or the daily splits, but all the cumulative deaths in the daily splits were increased if they were corrected, not just Jan 19.

You can see this in the dailyDeceasedCount field for the prefecture splits and compare it with previous version to see what the diff is.

If you like to explore the data more, see https://data.covid19japan.com/explore/# which allows you to visually check all the numbers going back 3 months.

**Comment by Ryllau** [comment]
Awesome! That link is very helpful! I appreciate the help. I think we have it all sorted out now.
